djangoAppTest/blog/urls.py
#Blog Urls

from django.urls import path
from .views import  about, blog, blog_detail


app_name = 'blog'

urlpatterns = [
    path('' , blog , name='blg'),
    path('about/', about, name= 'about'),
    path('blog-detail/<slug:slug>/', blog_detail, name='blog-detail')
]

djangoAppTest/myfirstdjango/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from blog import views
from user import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls", namespace='blog')),
    path('', include("user.urls", namespace='user') ),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

djangoAppTest/user/urls.py
# User Urls

from django.urls import path
from .views import login, register

app_name = 'user'

urlpatterns = [
    path('login/' , login, name='login'),
    path('register/' , register, name='register'),
]

djangoAppTest/blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Blog(models.Model):

    CATS ={
        (1, 'sport'),
        (2, 'fashion'),
        (3, 'technology'),
        (4, 'politics')
    }

    title = models.CharField(max_length=127, null=True, blank=True)
    text = models.TextField(help_text='Bura esas melumati daxil edin...')
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=63, verbose_name='Muellif', )
    cats = models.IntegerField(max_length=100, choices=CATS, default=1)
    blog_tags = models.ManyToManyField('Tag')
    slug = models.SlugField(max_length=255, null=True)

    def get_absolute_url(self):
        return reverse('blog:blog-detail', args=[self.slug])

    class Meta:
        verbose_name = "Blog"
        verbose_name_plural = "Blogs"
        ordering = ('created_at',)


  


    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=63, null=True, blank=True)

    def __str__(self):
        return self.title


        
 

djangoAppTest/user/models.py
from django.db import models


# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=127, null=True, blank=True)
    email = models.TextField(help_text='Bura emailinizi daxil edin...')
    
    confPassword = models.CharField(max_length=63, verbose_name='Muellif', )

djangoAppTest/user/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import User



class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields= ['username', 'email', 'password1', 'password2']
        

djangoAppTest/blog/views.py
# Blog Views
from django.shortcuts import get_object_or_404, render
from .models import Blog

# Create your views here.


def about(request):
    return render(request, 'about.html')

def blog(request):
    blogs = Blog.objects.all()
    return render(request, 'blogs.html', {'blogs':blogs})

def blog_detail(request, slug):
    blogs = get_object_or_404(Blog, slug=slug)
    return render(request, 'blog-details.html', {'blogs': blogs})

djangoAppTest/user/views.py
# User Views

from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm


# Create your views here.


def login(request):
    context={}
    return render(request, 'login.html')

def register(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
        
        
    context ={"form":form}
    return render(request, 'register.html', context)

djangoAppTest/blog/templates/about.html
{% extends "base.html" %}
{% block content %}
{% filter force_escape|lower %}
ABOUT PAGE

{% endfilter %}
{% endblock  %}
 

djangoAppTest/blog/templates/base.html
      <!doctype html>
      <html lang="en">
        <head>
          <!-- Required meta tags -->
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      
          <!-- Bootstrap CSS -->
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      
          <title>Hello, world!</title>
        </head>
        <body>
          {% include 'includes/navbar.html' %}
          {% block content %}
          
          
          {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

djangoAppTest/blog/templates/blog-details.html
{% extends "base.html" %}

{% block content %}



<h1>{{blogs.title}}</h1>



{% endblock  %}

djangoAppTest/blog/templates/blogs.html
{% extends "base.html" %}

{% load static custom_filter custom_tag %}
{% block content %}


<h1>Blog Page</h1>
{% for blog in blogs %} 
<h3> Blog - {{ forloop.counter }} </h3>

<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{% static 'uploads/food.jpg' %}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{blog.title|truncatechars:5}}</h5>
    <p class="card-text">{{blog.text|my_uppercase }}</p>
    <p class="card-text">Created: {{blog.created_at}}</p>
    {% current_time "%Y:%M:%D" as the_time %}
    <p class="card-text">My custom tag for date : {{ the_time }}</p>
    <a href="{{blog.get_absolute_url}}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
{% empty %}
<p>Blog is not available</p>

{% endfor %}


{% endblock  %}


   



   

djangoAppTest/blog/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:blg' %}">Blogs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:about' %}">About</a>
        </li>
        
      </ul>
    </div>
  </nav>

djangoAppTest/blog/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Index Page</h1>
{% endblock  %}

djangoAppTest/user/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS v5.0.2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>
  <body>
    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
              <div class="card text-black" style="border-radius: 25px;">
                <div class="card-body p-md-5">
                  <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
      
                      <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
      
                      <form class="mx-1 mx-md-4">  
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <input type="email" id="form3Example3c" class="form-control" />
                            <label class="form-label" for="form3Example3c">Your Email</label>
                          </div>
                        </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <input type="password" id="form3Example4c" class="form-control" />
                            <label class="form-label" for="form3Example4c">Password</label>
                          </div>
                        </div>
      
                        <div class="form-check d-flex justify-content-center mb-5">
                          <input
                            class="form-check-input me-2"
                            type="checkbox"
                            value=""
                            id="form2Example3c"
                          />
                        </div>
      
                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                          <button type="button" class="btn btn-primary btn-lg">Login</button>
                        </div>
                      </form>
      
                    </div>
                    <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
      
                      <img src="https://mdbootstrap.com/img/Photos/new-templates/bootstrap-registration/draw1.png" class="img-fluid" alt="Sample image">
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

djangoAppTest/user/templates/register.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS v5.0.2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>
  <body>
    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
              <div class="card text-black" style="border-radius: 25px;">
                <div class="card-body p-md-5">
                  <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
      
                      <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
      
                      <form class="mx-1 mx-md-4" method="POST">
                        {% csrf_token %}
                        {{form.as_p}}
                        
                          <input type="submit" name="Create User">
                      </form>
      
                    </div>
                    <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
      
                      <img src="https://mdbootstrap.com/img/Photos/new-templates/bootstrap-registration/draw1.png" class="img-fluid" alt="Sample image">
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>